### ISSUE TITLE
Addthis is not defined

### ISSUE THREAD

**Issue by oshaikh13** [farrukhshahzad/JS-NetSim#11]
When starting index.html, the console shows that addthis is undefined. 

Uncaught ReferenceError: addthis is not defined: 
jquery.min.js: 16

**Comment by farrukhshahzad** [comment]
Yes. Need to troubleshoot. This happens after recent merge with PR#10

**Comment by farrukhshahzad** [comment]
Please see why it is not working after yesterday's merge.

**Comment by farrukhshahzad** [comment]
Is this issue fixed now?

**Comment by oshaikh13** [comment]
Resolved in #14
