### ISSUE TITLE
Translate Networks to fit in view

### ISSUE THREAD

**Issue by oshaikh13** [farrukhshahzad/JS-NetSim#15]
The nodes and links in the JSON files should be translated by about 20 or so pixels left so they fit in the SVG viewfinder.

**Comment by farrukhshahzad** [comment]
This could problem in json. I will look into it. Also we have following format of json now:

```
{
    "directed": false,
    "multigraph": false, 
    "graph": {
       "width": 600, 
        "drag": true, 
        "r": 60, 
        "name": "8 - N=387(32), D=11.5, R=10.0 m", 
        "height": 500
    }, 
    "nodes": [..],
    "links": [..]
}
```

**Comment by farrukhshahzad** [comment]
I think the new josn will fix this.
